/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.org.rfdouro.calcgraus;

import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;

/**
 *
 * @author romulo
 */
public class FrmMain extends javax.swing.JFrame {

 /**
  * Creates new form FrmMain
  */
 public FrmMain() {
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jTabbedPane1 = new javax.swing.JTabbedPane();
  jPanel1 = new javax.swing.JPanel();
  edtCoordDec = new javax.swing.JTextField();
  jLabel1 = new javax.swing.JLabel();
  jButton1 = new javax.swing.JButton();
  jLabel2 = new javax.swing.JLabel();
  edtCoordResDec = new javax.swing.JTextField();
  jPanel2 = new javax.swing.JPanel();
  jLabel3 = new javax.swing.JLabel();
  edtCoordGeo = new javax.swing.JTextField();
  jButton2 = new javax.swing.JButton();
  jLabel4 = new javax.swing.JLabel();
  edtCoordResGeo = new javax.swing.JTextField();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  edtCoordDec.setText("-12.145341434999921");

  jLabel1.setText("Digite a coordenada");

  jButton1.setText("Converter");
  jButton1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton1ActionPerformed(evt);
   }
  });

  jLabel2.setText("Resultado");

  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
  jPanel1.setLayout(jPanel1Layout);
  jPanel1Layout.setHorizontalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(edtCoordDec)
     .addGroup(jPanel1Layout.createSequentialGroup()
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel1)
       .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
       .addComponent(jLabel2))
      .addGap(0, 147, Short.MAX_VALUE))
     .addComponent(edtCoordResDec))
    .addContainerGap())
  );
  jPanel1Layout.setVerticalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel1)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(edtCoordDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jButton1)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
    .addComponent(jLabel2)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(edtCoordResDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(31, 31, 31))
  );

  jTabbedPane1.addTab("Coordenadas decimais", jPanel1);

  jLabel3.setText("Digite a coordenada");

  edtCoordGeo.setText("-12°8'43.229''");

  jButton2.setText("Converter");
  jButton2.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton2ActionPerformed(evt);
   }
  });

  jLabel4.setText("Resultado");

  javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
  jPanel2.setLayout(jPanel2Layout);
  jPanel2Layout.setHorizontalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(edtCoordGeo)
     .addGroup(jPanel2Layout.createSequentialGroup()
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel3)
       .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
       .addComponent(jLabel4))
      .addGap(0, 147, Short.MAX_VALUE))
     .addComponent(edtCoordResGeo))
    .addContainerGap())
  );
  jPanel2Layout.setVerticalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel3)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(edtCoordGeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jButton2)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
    .addComponent(jLabel4)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(edtCoordResGeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(31, 31, 31))
  );

  jTabbedPane1.addTab("Coordenadas geográficas", jPanel2);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jTabbedPane1)
    .addContainerGap())
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jTabbedPane1)
    .addContainerGap())
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  MathContext mc = new MathContext(17, RoundingMode.HALF_UP);
  BigDecimal num = new BigDecimal(edtCoordDec.getText());

  boolean isNeg = num.doubleValue() < 0;
  if (isNeg) {
   num = num.negate();
  }

  Long d = num.longValue();

  BigDecimal _m = num.subtract(BigDecimal.valueOf(d));
  Long m = _m.multiply(BigDecimal.valueOf(60)).longValue();

  BigDecimal _s = num.subtract(BigDecimal.valueOf(d));
  BigDecimal __m = BigDecimal.valueOf(m).divide(BigDecimal.valueOf(60), mc);

  _s = _s.subtract(__m);
  _s = _s.multiply(BigDecimal.valueOf(3600), mc);

  if (isNeg)
   edtCoordResDec.setText("-" + d + "o " + m + "' " + _s + "'' ");
  else
   edtCoordResDec.setText("" + d + "o " + m + "' " + _s + "'' ");
 }//GEN-LAST:event_jButton1ActionPerformed

 private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  MathContext mc = new MathContext(17, RoundingMode.HALF_UP);
  String t = edtCoordGeo.getText();
  String sd = t.substring(0, t.indexOf("°"));
  String sm = t.substring(t.indexOf("°") + 1, t.indexOf("'"));
  String ss = t.substring(t.indexOf("'") + 1, t.indexOf("''"));

  BigDecimal d = new BigDecimal(sd);
  boolean isNeg = d.doubleValue() < 0;
  if (isNeg) {
   d = d.negate();
  }
  
  d = d.add((new BigDecimal(sm)).divide(new BigDecimal(60), mc)).add((new BigDecimal(ss)).divide(new BigDecimal(3600)));
  

  if (isNeg)
   edtCoordResGeo.setText("-" + d.abs(mc));
  else
   edtCoordResGeo.setText("" + d.abs(mc));
 }//GEN-LAST:event_jButton2ActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new FrmMain().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JTextField edtCoordDec;
 private javax.swing.JTextField edtCoordGeo;
 private javax.swing.JTextField edtCoordResDec;
 private javax.swing.JTextField edtCoordResGeo;
 private javax.swing.JButton jButton1;
 private javax.swing.JButton jButton2;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JPanel jPanel1;
 private javax.swing.JPanel jPanel2;
 private javax.swing.JTabbedPane jTabbedPane1;
 // End of variables declaration//GEN-END:variables
}
